import {
    Bell as BellIcon,
    BarChart3 as BarChartIcon,
    LayoutDashboard as LayoutDashboardIcon,
    Users as UserGroupIcon,
    Folder as FolderIcon,
    Trash2 as TrashIconLg,
    LifeBuoy as SupportIcon,
    Home as HomeIcon,
    Star as StaredIcon,
    RefreshCw as RefreshIcon,
    Flag as FlagIcon,
    Trash as TrashIcon,
    Archive as ArchiveIcon,
    MessageSquare as Message2Line,
    Paperclip as PaperclipIcon,
    Box as BoxIcon,
    ChevronRight as ChevronRightIcon,
    LayoutGrid as GridIcon,
    Box as BoxCubeIcon,
    Calendar as CalenderIcon,
    UserCircle as UserCircleIcon,
    ClipboardList as TaskIcon,
    MessageCircle as ChatIcon,
    Mail as MailIcon,
    FileText as DocsIcon,
    PieChart as PieChartIcon,
    ChevronDown as ChevronDownIcon,
    Calendar as Calendar2Line,
    Plug as PlugInIcon,
    File as PageIcon,
    Table as TableIcon,
    List as ListIcon,
    LogOut as LogoutIcon,
    Info as InfoCircleIcon,
    Settings as SettingsIcon,
    AlertCircle as ErrorIcon,
    CheckCircle as SuccessIcon,
    Info as InfoIcon,
    AlertTriangle as WarningIcon,
    Plus as PlusIcon,
    AlertOctagon as ErrorHexaIcon,
    Menu as MenuIcon,
    Check as CheckIcon,
    Mailbox as MailBox,
    Send as SendIcon,
    File as DraftIcon,
    MoreHorizontal as MoreDots,
    ClipboardCheck as ClipboardCheckIcon,
    Building2 as BuildingIcon,
    DoorOpen as DoorOpenIcon,
    Package as PackageIcon,
    Printer as PrinterIcon,
    ShieldCheck as ShieldCheckIcon,
    Wrench as WrenchIcon,
    X as CloseIcon,
    Database as DatabaseIcon,
    Eye as EyeIcon,
    EyeOff as EyeOffIcon,
    ArrowRight as ArrowRightIcon,
    LogIn as LoginIcon,
    Cloud as CloudIcon,
    Shield as ShieldIcon,
    Terminal as TerminalIcon,
    Pencil as PencilIcon,
    Play as PlayIcon,
    CheckCircle as CheckCircleIcon,
    Filter as FilterIcon,
    Layers as LayersIcon,
    FileText as FileTextIcon,
    Banknote as BanknoteIcon,
    Image as ImageIcon,
    Search as SearchIcon,
} from 'lucide-vue-next';

export {
    BellIcon,
    BarChartIcon,
    LayoutDashboardIcon,
    UserGroupIcon,
    FolderIcon,
    TrashIconLg,
    SupportIcon,
    HomeIcon,
    StaredIcon,
    RefreshIcon,
    FlagIcon,
    TrashIcon,
    ArchiveIcon,
    Message2Line,
    PaperclipIcon,
    BoxIcon,
    ChevronRightIcon,
    GridIcon,
    BoxCubeIcon,
    CalenderIcon,
    UserCircleIcon,
    TaskIcon,
    ChatIcon,
    MailIcon,
    DocsIcon,
    PieChartIcon,
    ChevronDownIcon,
    Calendar2Line,
    PlugInIcon,
    PageIcon,
    TableIcon,
    ListIcon,
    LogoutIcon,
    InfoCircleIcon,
    SettingsIcon,
    ErrorIcon,
    SuccessIcon,
    InfoIcon,
    WarningIcon,
    PlusIcon,
    ErrorHexaIcon,
    FilterIcon,
    MenuIcon,
    CheckIcon,
    MailBox,
    SendIcon,
    DraftIcon,
    MoreDots,
    ClipboardCheckIcon,
    BuildingIcon,
    DoorOpenIcon,
    PackageIcon,
    PrinterIcon,
    ShieldCheckIcon,
    WrenchIcon,
    CloseIcon,
    DatabaseIcon,
    EyeIcon,
    EyeOffIcon,
    ArrowRightIcon,
    LoginIcon,
    CloudIcon,
    ShieldIcon,
    TerminalIcon,
    PencilIcon,
    PlayIcon,
    CheckCircleIcon,
    LayersIcon,
    FileTextIcon,
    BanknoteIcon,
    ImageIcon,
    SearchIcon,
};
